name: 04 - Using Actions

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # 0. Checkout the code from the repository
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Printing Folders
              run: ls

        # 1. Install deps of our react application+
        # 2. Execute automated tests