name: 06 - Contexts
run-name: 06 - Contexts | DEBUG - ${{ inputs.debug }}

on:
    push:
    workflow_dispatch:
      inputs:
        debug:
          type: boolean
          default: false


env:
  MY_WORKFLOW_VAR: "workflow"
  MY_OVERWRITTEN_VAR: "workflow"

jobs:
    echo-data:
        runs-on: ubuntu-latest
        env:
          MY_JOB_VAR: "job"
          MY_OVERWRITTEN_VAR: "job"
        steps:
            - name: Display information
              run: |
                echo "Event Name: ${{ github.event_name }}"
                echo "Ref: ${{ github.ref }}"
                echo "SHA: ${{ github.sha }}"
                echo "Actor: ${{ github.actor }}"
                echo "Worflow: ${{ github.workflow }}"
                echo "Run ID: ${{ github.run_id }}"
                echo "Run number: ${{ github.run_number }}"
            - name: Retrieve variable
              run: |
                echo "Variable value: ${{ vars.MY_VAR }}"
            - name: Print env variables 01
              env:
                MY_STEP_VAR: "step"
                MY_OVERWRITTEN_VAR: "step"
              run: |
                echo "Workflow env ${{ env.MY_WORKFLOW_VAR }}"
                echo "Overwritten env ${{ env.MY_OVERWRITTEN_VAR }}"
            - name: Print env variables 02
              run: |
                echo "Workflow env ${{ env.MY_WORKFLOW_VAR }}"
                echo "Overwritten env ${{ env.MY_OVERWRITTEN_VAR }}"